### PR TITLE
Resolve checkstyle issues

### PR DESCRIPTION
**Pull request by stratika**
#### Description

This PR resolves some style issues that regard spacing, unused packages, unfolded packages, etc. and they were pointed by the command:
```bash
make checkstyle
```

#### Backend/s tested

Mark the backends affected by this PR.

- [ ] OpenCL
- [ ] PTX
- [ ] SPIRV

#### OS tested

Mark the OS where this PR is tested.

- [ ] Linux
- [ ] OSx
- [ ] Windows

#### Did you check on FPGAs?

If it is applicable, check your changes on FPGAs.

- [ ] Yes
- [ ] No

#### How to test the new patch?

```bash
make checkstyle
```

----------------------------------------------------------------------------

### CODE REVIEW

**Review by mairooni — APPROVED** [review]
LGTM

**Comment by mikepapadim** [comment]
it looks like these errors have been autogenerated by a miss-configured formatter

**Review by mikepapadim — APPROVED** [review]
LGTM

**Comment by jjfumero** [comment]
We need to revisit the instructions regarding code formatting in the latest version of IntelliJ.

**Review by jjfumero — APPROVED** [review]

**Pull request merged**
