### PR TITLE
Reverse usage of String Templates in preparation for JDK23

### PR DESCRIPTION
**Pull request by mikepapadim**
#### Description

Reverse the usage of String templates as they are going to be removed from JDK23.
#### Problem description

If the patch provides a fix for a bug, please describe what was the issue and how to reproduce the issue.

#### Backend/s tested

Mark the backends affected by this PR.

- [x] OpenCL
- [ ] PTX
- [ ] SPIRV

#### OS tested

Mark the OS where this PR is tested.

- [X] Linux
- [ ] OSx
- [ ] Windows

#### Did you check on FPGAs?

If it is applicable, check your changes on FPGAs.

- [ ] Yes
- [ ] No

#### How to test the new patch?

```bash
make jdk21 
```
----------------------------------------------------------------------------

### CODE REVIEW

**Review by mairooni — APPROVED** [review]

**Comment by stratika** [comment]
Is this PR only for the OpenCL backend? We use the String templates in PTX and SPIR-V, right?

**Comment by mikepapadim** [comment]
This now covers PTX and SPIRV @jjfumero @stratika

**Review by stratika — APPROVED** [review]
LGTM, thanks!

**Review by jjfumero — APPROVED** [review]
LGTM

**Pull request merged**
