### PR TITLE
Add javadocs #35

### PR DESCRIPTION
**Pull request by luisa-poeschl**
I added javadocs for everything I understood but for some methods I couldn't come up with a description, sorry

### CODE REVIEW

**Comment by jjfumero** [comment]
Thank you for your interest and contributions to the TornadoVM project!
Please note that all PRs are submitted to the `develop` branch of TornadoVM.

Additionally, we have developed a set of contributions guidelines which you can consult:
https://github.com/beehive-lab/TornadoVM/blob/master/CONTRIBUTIONS.md
Also, please take a look at the coding conventions we follow. There are some guidelines for Eclipse and IntelliJ.

Typically, the addition of Javadoc for the examples submodule of the TornadoVM project refers to the addition of documentation at the class-level to describe, for each example, how the TornadoVM API and task-schedules are composed, and used. 

I will update the issue with a better description.

Here you can see an example of what we are looking for:
https://github.com/beehive-lab/TornadoVM/blob/master/examples/src/main/java/uk/ac/manchester/tornado/examples/polyglot/HelloPython.java#L26-L38

It would be great if you could augment your PR accordingly following the instructions above.

**Comment by marco-schmidt** [comment]
> Additionally, we have developed a set of contributions guidelines which you can consult:
> https://github.com/beehive-lab/TornadoVM/blob/master/CONTRIBUTIONS.md

@jjfumero This should be https://github.com/beehive-lab/TornadoVM/blob/master/CONTRIBUTING.md, right?

**Comment by jjfumero** [comment]
Yes, we moved the file recently.

**Comment by jjfumero** [comment]
Hi @luisa-poeschl , are you still interested in solving this PR based on the feedback provided?

**Comment by jjfumero** [comment]
Due to inactivity related to this PR, I suggest closing it. Please, if you have new contributions feel free to open new PRs.

**Pull request closed without merging**
