### PR TITLE
Enable Partial Loop Unroll for all Backends

### PR DESCRIPTION
**Pull request by jjfumero**
#### Description

This patch enhances the JIT compiler with a phase for partial loop unroll and full loop unroll suggestions for SPIR-V.

In a nutshell: 
1. It introduces a full loop unroll suggestion for the SPIR-V compiler. 
2. It introduces partial loop unroller for the PTX compiler.
3. It fixes the partial loop unroll configuration for OpenCL 
4. It enables partial loop unroll for OpenCL 

Note that the partial loop unroll flag is **off** by default, since more experimentation is needed.  If `ON`, there are some tests failing (~14) due to some failures in the Graal JIT compiler. However, for some compute applications this optimisations must be beneficial, and, in the case of the SPIR-V, it works in combination of SPIR-V unroll suggestions as well as explicit loop unroll. 

#### Problem description

n/ a.

#### Backend/s tested

Mark the backends affected by this PR.

- [X] OpenCL
- [X] PTX
- [X] SPIRV

#### OS tested

Mark the OS where this PR is tested.

- [X] Linux
- [ ] OSx
- [ ] Windows

#### Did you check on FPGAs?

If it is applicable, check your changes on FPGAs.

- [ ] Yes
- [X] No

#### How to test the new patch?

```bash

## In the case of SPIR-V
make BACKEND=spirv

tornado-test --printKernel --jvm="-Dgraph.mv.device=0:0" -V uk.ac.manchester.tornado.unittests.compute.ComputeTests#matrixVector
```

A section of the generated code is as follows:

```llvm
   %B3_kernel0 = OpLabel 
   %102 = OpPhi %float {%55 %B2_kernel0} {%101 %B4_kernel0} 
   %104 = OpPhi %uint {%56 %B2_kernel0} {%103 %B4_kernel0} 
   %105 = OpSLessThan %bool %104 %51
   OpLoopMerge %B5_kernel0 %B4_kernel0 Unroll          << Loop Unroll suggestion enabled
   OpBranchConditional %105 %B4_kernel0 %B5_kernel0 
```

Enabling explicit loop unroll:

```bash
tornado-test --printKernel --jvm="-Dgraph.mv.device=0:0 -Dtornado.experimental.partial.unroll=True" -V uk.ac.manchester.tornado.unittests.compute.ComputeTests#matrixVector
```

Run the previous command for each of the backends.

### CODE REVIEW

**Review by stratika — COMMENTED** [review]
In my system, with the flag enabled I see the following reports. Just for reference:

- OpenCL:
```bash
==================================================
FAILED TESTS
==================================================
uk.ac.manchester.tornado.unittests.foundation.TestIf#test06 - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.kernelcontext.matrices.TestMatrixMultiplicationKernelContext#mxm2DKernelContext01 - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.kernelcontext.matrices.TestMatrixMultiplicationKernelContext#mxm2DKernelContext02 - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.arrays.TestNewArrays#testInitNewArrayInsideParallelWithComplexAccesses - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.arrays.TestNewArrays#testInitNewArrayInsideParallel - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.codegen.CodeGenTest#test02 - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.compute.ComputeTests#testMandelbrot - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.compute.ComputeTests#testEuler - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.compute.ComputeTests#testJuliaSets - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testMultipleTasksMultipleCallees - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test01 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test02 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test03 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test04 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test05 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testVector01 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testSingleTask - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testMultipleTasks - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testNoDoubleCompilation - [WHITELISTED]: NO

==================================================
```

- PTX:
```bash
==================================================
FAILED TESTS
==================================================
uk.ac.manchester.tornado.unittests.kernelcontext.matrices.TestMatrixMultiplicationKernelContext#mxm2DKernelContext01 - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.kernelcontext.matrices.TestMatrixMultiplicationKernelContext#mxm2DKernelContext02 - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.arrays.TestNewArrays#testInitNewArrayInsideParallel - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.arrays.TestNewArrays#testInitNewArrayInsideParallelWithComplexAccesses - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.compute.ComputeTests#testMandelbrot - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.compute.ComputeTests#testEuler - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.compute.ComputeTests#testJuliaSets - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test01 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test02 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test03 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test04 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test05 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testVector01 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testMultipleTasksMultipleCallees - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testSingleTask - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testMultipleTasks - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testNoDoubleCompilation - [WHITELISTED]: NO

==================================================
```

- SPIR-V:
```bash
==================================================
FAILED TESTS
==================================================
uk.ac.manchester.tornado.unittests.kernelcontext.matrices.TestMatrixMultiplicationKernelContext#mxm2DKernelContext01 - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.kernelcontext.matrices.TestMatrixMultiplicationKernelContext#mxm2DKernelContext02 - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.arrays.TestNewArrays#testInitNewArrayInsideParallelWithComplexAccesses - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.arrays.TestNewArrays#testInitNewArrayInsideParallel - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.codegen.CodeGenTest#test02 - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.compute.ComputeTests#testMandelbrot - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.compute.ComputeTests#testEuler - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.compute.ComputeTests#testJuliaSets - [WHITELISTED]: YES
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test01 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test02 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test03 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test04 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#test05 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testVector01 - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testMultipleTasksMultipleCallees - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testSingleTask - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testMultipleTasks - [WHITELISTED]: NO
uk.ac.manchester.tornado.unittests.tasks.TestMultipleFunctions#testNoDoubleCompilation - [WHITELISTED]: NO

==================================================
```

**Comment by jjfumero** [comment]
> In my system, with the flag enabled I see the following reports. Just for reference:
> 
Yes, there are some tests failing when this flag is ON, It is expected. We will refine this in future iterations.

**Review by mikepapadim — APPROVED** [review]
LGTM

**Review by mairooni — APPROVED** [review]
LGTM

**Pull request merged**
