### PR TITLE
[release] TornadoVM 1.0.8

### PR DESCRIPTION
**Pull request by jjfumero**
Improvements
============
- #565: New API call in the Execution Plan to log/trace the executed configuration plans.
- #563: Expand the TornadoVM profiler with Level Zero Sysman Energy Metrics.
- #559: Refactoring Power Metric handlers for PTX and OpenCL.
- #548: Benchmarking improvements.
- #549: Prebuilt API tests added using multiple backend-setup.
- Add internal tests for monitoring memory management [link](https://github.com/beehive-lab/TornadoVM/commit/0644225a641bd859372743b59d46c6c9a4613337).

Compatibility
=============
- #561: Build for OSx 14.6 and OSx 15 fixed.

Bug Fixes
==============
- #564: Jenkins configuration fixed to run KFusion per backend.
- #562: Warmup action from the Execution Plan fixed to run with correct internal IDs.
- #557: Shared Execution Plans Context fixed.
- #553: OpenCL compiler flags for Intel Integrated GPUs fixed.
- #552: Fixed runtime to select any device among multiple SPIR-V devices.
- Fixed zero extend arithmetic operations: [link](https://github.com/beehive-lab/TornadoVM/commit/ea7b60263072ba0299da205cb920d0c68b3d1749).

#### Backend/s tested

Mark the backends affected by this PR.

- [X] OpenCL
- [X] PTX
- [X] SPIRV

#### OS tested

Mark the OS where this PR is tested.

- [X] Linux
- [ ] OSx
- [ ] Windows

#### Did you check on FPGAs?

If it is applicable, check your changes on FPGAs.

- [ ] Yes
- [X] No

#### How to test the new patch?

```bash
make
tornado --version

make tests

tornado-benchmarks.py --skipSequential
```

### CODE REVIEW

**Comment by jjfumero** [comment]
Ready for final review

**Review by stratika — APPROVED** [review]
LGTM

**Review by mairooni — APPROVED** [review]
LGTM

**Comment by jjfumero** [comment]
let's do the final testing:
[ ] KFusion
[ ] Ray-Tracer

**Review by mikepapadim — APPROVED** [review]

**Comment by stratika** [comment]
Just a confirmation, I have tested successfully:
- KFusion with `opencl` and `ptx`.
- TornadoVM-Ray-Tracer with `opencl` and `spirv`.

**Pull request merged**
